export const staticInitialList1 = [
  {
    id: 122996,
    docEntry: 122996,
    docNum: 22021752,
    docDate: "21/03/2023 12:00:00 AM",
    fromWhs: "RAP_Str",
    toWhs: "SbAsly",
    cardCode: "",
    cardName: "",
    itrDet: [
      {
        id: 0,
        docEntry: 122996,
        lineNum: 0,
        itemCode: "A-000558",
        itemName: "PLAIN WASHER M6 X Od: 16 x 2 THK",
        fromWhs: "RAP_Str",
        toWhs: "SbAsly",
        qty: 8,
        uoM: "Manual",
        locCode: 2,
        availableStock: "0.000000",
        qtyInStock: "0.000000",
        uomName: "NOS",
      },
      {
        id: 1,
        docEntry: 122996,
        lineNum: 1,
        itemCode: "A-002052",
        itemName: "SENSOR SHAFT. 3/4 X 430 MML.",
        fromWhs: "RAP_Str",
        toWhs: "SbAsly",
        qty: 2,
        uoM: "Manual",
        locCode: 2,
        availableStock: "71.000000",
        qtyInStock: "0.000000",
        uomName: "NOS",
      },
      {
        id: 6,
        docEntry: 122996,
        lineNum: 6,
        itemCode: "A-003052",
        itemName: "HEX NUT M 5 [HT]",
        fromWhs: "RAP_Str",
        toWhs: "SbAsly",
        qty: 4,
        uoM: "Manual",
        locCode: 2,
        availableStock: "0.000000",
        qtyInStock: "0.000000",
        uomName: "NOS",
      },
      {
        id: 7,
        docEntry: 122996,
        lineNum: 7,
        itemCode: "A-003053",
        itemName: "HEX NUT  M 6 (H.T.)",
        fromWhs: "RAP_Str",
        toWhs: "SbAsly",
        qty: 8,
        uoM: "Manual",
        locCode: 2,
        availableStock: "16515.000000",
        qtyInStock: "0.000000",
        uomName: "NOS",
      },
      {
        id: 9,
        docEntry: 122996,
        lineNum: 9,
        itemCode: "A-004716",
        itemName: "HEX BOLT M6 x 16 (HIGH TENSION)",
        fromWhs: "RAP_Str",
        toWhs: "SbAsly",
        qty: 4,
        uoM: "Manual",
        locCode: 2,
        availableStock: "1034.000000",
        qtyInStock: "0.000000",
        uomName: "NOS.",
      },
    ],
  },
];

export const staticInitialList2 = [
  {
    id: 1,
    docEntry: 1,
    docNum: 1,
    docDate: "01/02/2023",
    fromWhs: "General Warehouse 1",
    toWhs: "General Warehouse 2",
    cardCode: "V01270",
    cardName: "3I PUBLISHING PVT.LTD.",
    itrDet: [
      {
        id: 0,
        docEntry: 1,
        lineNum: 0,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
      {
        id: 1,
        docEntry: 1,
        lineNum: 1,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
    ],
  },

  {
    id: 2,
    docEntry: 2,
    docNum: 2,
    docDate: "01/02/2023",
    fromWhs: "General Warehouse 1",
    toWhs: "General Warehouse 2",
    cardCode: "V01270",
    cardName: "3I PUBLISHING PVT.LTD.",
    itrDet: [
      {
        id: 0,
        docEntry: 2,
        lineNum: 0,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
      {
        id: 1,
        docEntry: 2,
        lineNum: 1,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
    ],
  },

  {
    id: 3,
    docEntry: 3,
    docNum: 3,
    docDate: "01/02/2023",
    fromWhs: "General Warehouse 1",
    toWhs: "General Warehouse 2",
    cardCode: "V01270",
    cardName: "3I PUBLISHING PVT.LTD.",
    itrDet: [
      {
        id: 0,
        docEntry: 3,
        lineNum: 0,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
      {
        id: 1,
        docEntry: 3,
        lineNum: 1,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
    ],
  },

  {
    id: 4,
    docEntry: 4,
    docNum: 4,
    docDate: "01/02/2023",
    fromWhs: "General Warehouse 1",
    toWhs: "General Warehouse 2",
    cardCode: "V01270",
    cardName: "3I PUBLISHING PVT.LTD.",
    itrDet: [
      {
        id: 0,
        docEntry: 4,
        lineNum: 0,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
      {
        id: 1,
        docEntry: 4,
        lineNum: 1,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
    ],
  },
  {
    id: 5,
    docEntry: 5,
    docNum: 5,
    docDate: "01/02/2023",
    fromWhs: "General Warehouse 1",
    toWhs: "General Warehouse 2",
    cardCode: "V01270",
    cardName: "3I PUBLISHING PVT.LTD.",
    itrDet: [
      {
        id: 0,
        docEntry: 5,
        lineNum: 0,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
      {
        id: 1,
        docEntry: 5,
        lineNum: 1,
        itemCode: "A-006452",
        itemName: "SLIDER",
        fromWhs: "General Warehouse 1",
        toWhs: "General Warehouse 2",
        qty: "2.000000",
        uoM: "manual",
        locCode: "1",
      },
    ],
  },
];
